- name: install lamp 
  hosts: all
  become: yes
  vars: 
    info_path: /var/www/html/info.php
  tasks: 
    - name: check if the playbook is being executed on supported os
      ansible.builtin.fail:
        msg: "This playbook is designed to work on ubuntu and redhat only"
      when: ansible_facts['distribution'] != "Ubuntu" and ansible_facts['distribution'] != "RedHat"
    - name: install apache server 
      ansible.builtin.package: 
        name: "{{package_name}}"
        state: present
    - name: debug apache installed
      ansible.builtin.debug:
        msg: "Installed apache server using package {{ package_name }}"
    
    - name: enable and start apache  
      ansible.builtin.systemd: 
        name: "{{package_name}}"
        enabled: yes 
        state: started
    - name: debug apache service started
      ansible.builtin.debug:
        msg: "enabled and started apache"

    - name: install php server 
      ansible.builtin.package: 
        name: "{{ item }}"
        state: present
      loop: "{{ php_packages }}"
      notify:
        system restart  
    - name: debug php modules installed
      ansible.builtin.debug:
        msg: "installed php-packages {{ php_packages }} "
   
  
 

    - name: copy the info.php file 
      ansible.builtin.copy: 
        src: info.php 
        dest: "{{ info_path }}"
      notify:
        system restart  
    - name: debug info.php
      ansible.builtin.debug:
        msg: "created info.php at {{ info_path }}"

 
  handlers:
    - name: system restart 
      ansible.builtin.systemd:
        name: "{{package_name}}"
        state: restarted
