- name: install lamp on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: install apache2 
      ansible.builtin.apt: 
        name: apache2 
        update_cache: yes 
        state: present
    - name: install packages 
      ansible.builtin.apt: 
        name: 
          - php
          - libapache2-mod-php
          - php-mysql
        state: present 
    - name: copy file 
      ansible.builtin.copy:
        src: info.php 
        dest: /var/www/html/info.php
      notify: 
        system restart
  handlers:
    - name: system restart 
      ansible.builtin.systemd:
        name: apache2
        state: restarted
      